name: Trigger Playwright Tests via Webhook

on:
  push:
    branches: [main, master]

jobs:
  trigger-tests:
    runs-on: ubuntu-latest
    environment: PW_WEBHOOK_URL
    steps:
      - name: Trigger Webhook
        run: curl -X POST ${{ secrets.PW_WEBHOOK_URL }}/webhook
