name: Trigger Playwright Tests

on:
  push:
    branches:
      - main

jobs:
  trigger-tests:
    runs-on: ubuntu-latest
    steps:
      - name: Trigger Local Webhook
        run: |
          curl -X POST ${{ secrets.PW_WEBHOOK_URL }}/webhook
